export const TEAM_NAMES: string[] = [
  'Spider-Man',
  'Iron Man',
  'Captain America',
  'Thor',
  'Hulk',
  'Black Widow',
  'Hawkeye',
  'Wolverine',
  'Storm',
  'Cyclops',
  'Jean Grey',
  'Professor X',
  'Magneto',
  'Mystique',
  'Beast',
  'Rogue',
  'Gambit',
  'Nightcrawler',
  'Colossus',
  'Iceman',
  'Angel',
  'Psylocke',
  'Jubilee',
  'Kitty Pryde',
  'Deadpool',
  'Cable',
  'Domino',
  'Warpath',
  'Sunspot',
  'Cannonball',
  'Boom-Boom',
  'Wolfsbane',
  'Mirage',
  'Magik',
  'Havok',
  'Polaris',
  'Banshee',
  'Forge',
  'Bishop',
  'Emma Frost',
  'Quicksilver',
  'Scarlet Witch',
  'Vision',
  'Ant-Man',
  'Wasp',
  'Black Panther',
  'Doctor Strange',
  'Daredevil',
  'Luke Cage',
  'Jessica Jones',
  'Iron Fist',
  'Punisher',
  'Ghost Rider',
  'Blade',
  'Moon Knight',
  'She-Hulk',
  'Captain Marvel',
  'Ms. Marvel',
  'Spider-Woman',
  'Miles Morales',
  'Spider-Gwen',
  'Venom',
  'Carnage',
  'Green Goblin',
  'Doctor Octopus',
  'Sandman',
  'Lizard',
  'Electro',
  'Rhino',
  'Vulture',
  'Mysterio',
  'Kraven',
  'Thanos',
  'Loki',
  'Hela',
  'Ultron',
  'Red Skull',
  'Baron Zemo',
  'Kang',
  'Apocalypse',
  'Mr. Sinister',
  'Juggernaut',
  'Sabretooth',
  'Omega Red',
  'Bullseye',
  'Kingpin',
  'Dormammu',
  'Mephisto',
  'Shuma-Gorath',
  'Galactus',
  'Silver Surfer',
  'Nova',
  'Adam Warlock',
  'Star-Lord',
  'Gamora',
  'Drax',
  'Rocket Raccoon',
  'Groot',
  'Nebula',
  'Mantis',
  'Yondu',
  'Howard the Duck',
  'Nick Fury',
  'Maria Hill',
  'Peggy Carter',
  'Falcon',
  'Winter Soldier',
  'War Machine',
  'Rescue',
];

export function pickTeamNames(count: number, used: Set<string>): string[] {
  const available = TEAM_NAMES.filter((name) => !used.has(name));
  if (available.length < count) {
    throw new Error(`Not enough team names available (need ${count}, have ${available.length})`);
  }
  const shuffled = [...available];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled.slice(0, count);
}
